"""Add current_streak and total_reviews to Card model

Revision ID: 0f5e9998e34a
Revises: ceb12abb2820
Create Date: 2025-04-27 11:49:00.173152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5e9998e34a'
down_revision: Union[str, None] = 'ceb12abb2820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('total_reviews', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'total_reviews')
    op.drop_column('cards', 'current_streak')
    # ### end Alembic commands ###
