"""add comments table

Revision ID: 21c751e00c9d
Revises: 465d7ed30244
Create Date: 2025-06-22 16:46:25.638006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21c751e00c9d'
down_revision: Union[str, None] = '465d7ed30244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leaderboard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period', postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', name='leaderboardperiod'), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='leaderboard_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='leaderboard_pkey')
    )
    # ### end Alembic commands ###
