"""Add ondelete cascade for QuizAnswer session_id

Revision ID: 2696e923444f
Revises: 6fd1ce2e3bf8
Create Date: 2025-04-28 20:21:13.329159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2696e923444f'
down_revision: Union[str, None] = '6fd1ce2e3bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
