"""Add created_at to study_sessions

Revision ID: 2862826ab04a
Revises: af71cdfd0927
Create Date: 2025-04-25 21:41:51.209917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2862826ab04a'
down_revision: Union[str, None] = 'af71cdfd0927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_records', sa.Column('ease_factor', sa.Float(), nullable=True))
    op.add_column('study_records', sa.Column('interval', sa.Integer(), nullable=True))
    op.add_column('study_records', sa.Column('repetition_number', sa.Integer(), nullable=True))
    op.add_column('study_sessions', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_sessions', 'created_at')
    op.drop_column('study_records', 'repetition_number')
    op.drop_column('study_records', 'interval')
    op.drop_column('study_records', 'ease_factor')
    # ### end Alembic commands ###
