"""Set ondelete to SET NULL for quiz_sessions

Revision ID: 2c922b5a3897
Revises: f93bcbbee95c
Create Date: 2025-06-23 12:47:49.390055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c922b5a3897'
down_revision: Union[str, None] = 'f93bcbbee95c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
