"""Add ondelete cascade for QuizAnswer question_id

Revision ID: 3156e223437f
Revises: 3c8ce75c0ca7
Create Date: 2025-04-28 20:08:49.100966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3156e223437f'
down_revision: Union[str, None] = '3c8ce75c0ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quiz_questions_card_id_fkey', 'quiz_questions', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_questions', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_questions', type_='foreignkey')
    op.create_foreign_key('quiz_questions_card_id_fkey', 'quiz_questions', 'cards', ['card_id'], ['id'])
    # ### end Alembic commands ###
