"""add submitted_at to quiz_answers

Revision ID: 465d7ed30244
Revises: 6b4a0656b52b
Create Date: 2025-06-20 15:39:52.955714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465d7ed30244'
down_revision: Union[str, None] = '6b4a0656b52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_answers', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_answers', 'submitted_at')
    # ### end Alembic commands ###
