"""Add ondelete cascade for QuizSession deck_id

Revision ID: 600f59c708a7
Revises: bafc194a4eb4
Create Date: 2025-04-28 18:38:33.109269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600f59c708a7'
down_revision: Union[str, None] = 'bafc194a4eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quiz_sessions_deck_id_fkey', 'quiz_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_sessions', 'decks', ['deck_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_sessions', type_='foreignkey')
    op.create_foreign_key('quiz_sessions_deck_id_fkey', 'quiz_sessions', 'decks', ['deck_id'], ['id'])
    # ### end Alembic commands ###
