"""Add ondelete cascade for QuizAnswer session_id

Revision ID: 67aee09c8096
Revises: e257704f08ff
Create Date: 2025-04-28 20:16:46.092172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67aee09c8096'
down_revision: Union[str, None] = 'e257704f08ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_answers', 'question_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_answers', 'question_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
