"""Add ondelete cascade for QuizAnswer session_id

Revision ID: 6fd1ce2e3bf8
Revises: 67aee09c8096
Create Date: 2025-04-28 20:20:22.788089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd1ce2e3bf8'
down_revision: Union[str, None] = '67aee09c8096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
