"""Add ondelete cascade for QuizAnswer question_id

Revision ID: 787499122940
Revises: 600f59c708a7
Create Date: 2025-04-28 18:40:15.039965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '787499122940'
down_revision: Union[str, None] = '600f59c708a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quiz_answers_question_id_fkey', 'quiz_answers', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_answers', 'quiz_questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_answers', type_='foreignkey')
    op.create_foreign_key('quiz_answers_question_id_fkey', 'quiz_answers', 'quiz_questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
