"""add avatar column to users table

Revision ID: 96d0b9150401
Revises: d91c30a9ecf7
Create Date: 2025-05-02 10:58:36.996322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d0b9150401'
down_revision: Union[str, None] = 'd91c30a9ecf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add the column as nullable first
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    
    # Step 2: Set default value for existing rows
    op.execute("UPDATE users SET avatar = 'avatars/Ellipse1.png' WHERE avatar IS NULL")
    
    # Step 3: Make the column non-nullable
    op.alter_column('users', 'avatar', nullable=False,
                   server_default=sa.text("'avatars/Ellipse1.png'"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###