"""Add ondelete cascade to study_sessions deck_id foreign key

Revision ID: bafc194a4eb4
Revises: e3e16ae6705e
Create Date: 2025-04-27 12:52:05.212521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafc194a4eb4'
down_revision: Union[str, None] = 'e3e16ae6705e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('study_sessions_deck_id_fkey', 'study_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'study_sessions', 'decks', ['deck_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_sessions', type_='foreignkey')
    op.create_foreign_key('study_sessions_deck_id_fkey', 'study_sessions', 'decks', ['deck_id'], ['id'])
    # ### end Alembic commands ###
