"""Add ondelete cascade for QuizAnswer session_id

Revision ID: d91c30a9ecf7
Revises: 2696e923444f
Create Date: 2025-04-28 20:21:41.891590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91c30a9ecf7'
down_revision: Union[str, None] = '2696e923444f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_answers', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_answers', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
