"""Add cascade delete to Card relationships

Revision ID: e3e16ae6705e
Revises: 0f5e9998e34a
Create Date: 2025-04-27 12:40:38.402398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e16ae6705e'
down_revision: Union[str, None] = '0f5e9998e34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
