"""Add ondelete cascade for QuizAnswer question_id

Revision ID: f23e3231b4d7
Revises: 3156e223437f
Create Date: 2025-04-28 20:15:17.758652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23e3231b4d7'
down_revision: Union[str, None] = '3156e223437f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_sessions', 'deck_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_sessions', 'deck_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
