"""Set ondelete to SET NULL for quiz and study sessions

Revision ID: f93bcbbee95c
Revises: 21c751e00c9d
Create Date: 2025-06-23 12:41:23.913219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93bcbbee95c'
down_revision: Union[str, None] = '21c751e00c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_sessions', 'deck_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('study_sessions_deck_id_fkey', 'study_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'study_sessions', 'decks', ['deck_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_sessions', type_='foreignkey')
    op.create_foreign_key('study_sessions_deck_id_fkey', 'study_sessions', 'decks', ['deck_id'], ['id'], ondelete='CASCADE')
    op.alter_column('study_sessions', 'deck_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
